version: '3.3'
services:
  nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: nacos
    restart: always
    ports:
      - 8848:8848
    environment:
      # 支持主机名可以使用hostname,否则使用ip，默认ip
      - PREFER_HOST_MODE=ip
      # 单机模式
      - MODE=standalone
      # 数据源平台 支持mysql或不保存empty
      #- SPRING_DATASOURCE_PLATFORM=mysql
      # mysql配置，!!!attention必须是mysql所在主机IP
      #- MYSQL_SERVICE_HOST=192.168.0.123
      #- MYSQL_SERVICE_PORT=3306
      #- MYSQL_SERVICE_USER=root
      #- MYSQL_SERVICE_PASSWORD=123456
      #- MYSQL_SERVICE_DB_NAME=nacos
    volumes:
      - nacos-logs:/home/nacos/logs
      - nacos-conf:/home/nacos/conf

volumes:
  nacos-conf:
  nacos-logs: