version: '3.3'
services:
  docker-fe-01:
    image: "apache/doris:2.0.0_alpha-fe-x86_64"
    container_name: "doris-fe-01"
    hostname: "fe-01"
    environment:
      - FE_SERVERS=fe1:${FE01_HOST}:9010,fe2:${FE02_HOST}:9010,fe3:${FE03_HOST}:9010
      - FE_ID=1
    #ports:
    #  - 8031:8030
    #  - 9031:9030
    volumes:
      - ./data/fe-01/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./data/fe-01/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: ${FE01_HOST}

  docker-fe-02:
    image: "apache/doris:2.0.0_alpha-fe-x86_64"
    container_name: "doris-fe-02"
    hostname: "fe-02"
    environment:
      - FE_SERVERS=fe1:${FE01_HOST}:9010,fe2:${FE02_HOST}:9010,fe3:${FE03_HOST}:9010
      - FE_ID=2
    #ports:
    #  - 8032:8030
    #  - 9032:9030
    volumes:
      - ./data/fe-02/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./data/fe-02/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: ${FE02_HOST}

  docker-fe-03:
    image: "apache/doris:2.0.0_alpha-fe-x86_64"
    container_name: "doris-fe-03"
    hostname: "fe-03"
    environment:
      - FE_SERVERS=fe1:${FE01_HOST}:9010,fe2:${FE02_HOST}:9010,fe3:${FE03_HOST}:9010
      - FE_ID=3
    #ports:
    #  - 8033:8030
    #  - 9033:9030
    volumes:
      - ./data/fe-03/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./data/fe-03/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: ${FE03_HOST}

  docker-be-01:
    image: "apache/doris:2.0.0_alpha-be-x86_64"
    container_name: "doris-be-01"
    hostname: "be-01"
    depends_on:
      - docker-fe-01
      - docker-fe-02
      - docker-fe-03
    environment:
      - FE_SERVERS=fe1:${FE01_HOST}:9010,fe2:${FE02_HOST}:9010,fe3:${FE03_HOST}:9010
      - BE_ADDR=${BE01_HOST}:9050
    #ports:
    #  - 8041:8040
    volumes:
      - ./data/be-01/storage:/opt/apache-doris/be/storage
      - ./data/be-01/script:/docker-entrypoint-initdb.d
      - ./data/be-01/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: ${BE01_HOST}

  docker-be-02:
    image: "apache/doris:2.0.0_alpha-be-x86_64"
    container_name: "doris-be-02"
    hostname: "be-02"
    depends_on:
      - docker-fe-01
      - docker-fe-02
      - docker-fe-03
    environment:
      - FE_SERVERS=fe1:${FE01_HOST}:9010,fe2:${FE02_HOST}:9010,fe3:${FE03_HOST}:9010
      - BE_ADDR=${BE02_HOST}:9050
    #ports:
    #  - 8042:8040
    volumes:
      - ./data/be-02/storage:/opt/apache-doris/be/storage
      - ./data/be-02/script:/docker-entrypoint-initdb.d
      - ./data/be-02/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: ${BE02_HOST}

  docker-be-03:
    image: "apache/doris:2.0.0_alpha-be-x86_64"
    container_name: "doris-be-03"
    hostname: "be-03"
    depends_on:
      - docker-fe-01
      - docker-fe-02
      - docker-fe-03
    environment:
      - FE_SERVERS=fe1:${FE01_HOST}:9010,fe2:${FE02_HOST}:9010,fe3:${FE03_HOST}:9010
      - BE_ADDR=${BE03_HOST}:9050
    #ports:
    #  - 8043:8040
    volumes:
      - ./data/be-03/storage:/opt/apache-doris/be/storage
      - ./data/be-03/script:/docker-entrypoint-initdb.d
      - ./data/be-03/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: ${BE03_HOST}

  nginx:
    image: nginx:1.19.2-alpine
    container_name: "doris-nginx"
    hostname: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/log/:/var/log/nginx/
    ports:
      - 9030:9030
      - 8030:8030
      #- 8040:8040
    depends_on:
      - docker-fe-01
      - docker-fe-02
      - docker-fe-03
      - docker-be-01
      - docker-be-02
      - docker-be-03
    networks:
      doris_net:
        ipv4_address: ${NGINX_HOST}
networks:
  doris_net:
    ipam:
      config:
        - subnet: ${SUBNET}