# 全局配置
global:
  # 多久采集一次数据
  scrape_interval: 15s
  # 采集时的超时时间
  scrape_timeout: 10s
# 告警通知
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 127.0.0.1:9093
# 告警alert规则
rule_files:
  - "/usr/local/prometheus/rules/*.rules"

# 监控采集任务
scrape_configs:
  # web服务
  - job_name: 'web-server'
    # 采集的路径
    metrics_path: '/api/actuator/prometheus'
    # 采集服务的地址
    static_configs:
      - targets: ['127.0.0.1:8081']
    # MySQL
  - job_name: 'mysql'
    static_configs:
      - targets: ['127.0.0.1:9104']
    # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['127.0.0.1:9121']
    # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['127.0.0.1:9913']
    # 服务器
  - job_name: 'server'
    static_configs:
      - targets: ['127.0.0.1:9100']