version: '3.3'
services:
  confluence:
    image: 'haxqer/confluence:7.19.9'
    container_name: confluence
    ports:
      - '8090:8090'
    environment:
      - TZ=Asia/Shanghai
#    extra_hosts:
#      - host.docker.internal:host-gateway
    depends_on:
      - confluence_db
    volumes:
      - './backups:/var/atlassian/application-data/confluence/backups'
  confluence_db:
    image: 'mysql:latest'
    container_name: confluence_db
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=Ysj666666'
