version: '3.3'
services:
  oracle:
    image: registry.aliyuncs.com/helowin/oracle_11g
    container_name: oracle
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 1521:1521
    volumes:
      - ./dpdump:/home/oracle/app/oracle/admin/orcl/dpdump/
    privileged: true
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 500M