version: "3.3"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - '9004:9000'
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'

