version: '3.3'

# 分布式任务管理平台
# http://localhost:8080/xxl-job-admin/
# 账号密码 admin/123456
services:
  mysql:
    image: mysql
    container_name: xxl-mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=xxl_job"
    ports:
      - "3306:3306"
    networks:
      - xxl
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file /docker-entrypoint-initdb.d/tables_xxl_job.sql'
    volumes:
      - './tables_xxl_job.sql:/docker-entrypoint-initdb.d/tables_xxl_job.sql'
      - 'xxl-mysql-conf:/etc/mysql/conf.d'
      - 'xxl-mysql-logs:/logs'
      - 'xxl-mysql-data:/var/lib/mysql'
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.1
    container_name: xxl-job-admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - xxl
    environment:
      #  https://github.com/xuxueli/xxl-job/blob/master/xxl-job-admin/src/main/resources/application.properties
      PARAMS: '--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8
                --spring.datasource.username=root
                --spring.datasource.password=123456'

networks:
  xxl:
    driver: bridge

volumes:
  xxl-mysql-conf:
  xxl-mysql-logs:
  xxl-mysql-data:
