version: '3.3'
services:
  alertmanager:
    ports:
      - '9093:9093'
    restart: always
    container_name: alertmanager
    volumes:
      - './alertmanager.yml:/etc/alertmanager/alertmanager.yml'
    image: prom/alertmanager