version: '3.3'

# CI/CD
services:
  blueocean:
    image: jenkinsci/blueocean
    container_name: jenkins
    ports:
      - '9095:8080'
      - '50000:50000'
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - './apache-maven-3.5.4:/usr/local/maven'
      - '/etc/localtime:/etc/localtime'
      - '/var/run/docker.sock:/var/run/docker.sock'
