version: '3.3'

# CI/CD
services:
  blueocean:
    image: jenkinsci/blueocean
    container_name: jenkins
    user: root
    ports:
      - '12908:8080'
      #- '50000:50000'
    volumes:
      - './jenkins_home:/var/jenkins_home'
      - './apache-maven-3.5.3:/usr/local/maven'
      #- '/usr/local/git:/var/local/git'
      - '/etc/localtime:/etc/localtime'
      - '/var/run/docker.sock:/var/run/docker.sock'
