version: '3.3'

# 服务监控
services:
  serverstatus:
    restart: unless-stopped
    container_name: serverstatus
    volumes:
      - './config.json:/ServerStatus/server/config.json'
      - './serverstatus-monthtraffic:/usr/share/nginx/html/json'
    ports:
      - '8880:80'
      - '35601:35601'
    image: 'cppla/serverstatus:latest'
