version: '3.3'
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: music
    user: 0:0
    ports:
      - '4533:4533'
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - './data:/data'
      - './music:/music'
