version: '3.3'

# 青龙面板
services:
  qinglong:
    # 建议安装2.11.3稳定版本
    # 一键安装相关依赖(解决安装node, python依赖失败问题): https://github.com/FlechazoPh/QLDependency
    # docker exec -it qinglong bash -c "$(curl -fsSL https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | bash)"
    image: 'whyour/qinglong:2.11.3'
    container_name: qinglong
    restart: unless-stopped
    volumes:
      - './ql:/ql/data'
    ports:
      - '5700:5700'
#      - '5701:5701'
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_TG_BOT=true
      - ENABLE_WEB_PANEL=true

