version: '3.3'

# 埋点
services:
  webfunny_monitor:
    image: webfunny/webfunny_monitor:3.1.22-beta
    restart: always
    container_name: webfunny_monitor
    volumes:
      - './app:/app'
    ports:
      - '8008-8015:8008-8015'