version: '3.3'

# 系统监控
services:
  glances:
    restart: unless-stopped
    ports:
      - '61208-61209:61208-61209'
    environment:
      - GLANCES_OPT=-w
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    pid: host
    image: 'nicolargo/glances:latest-full'
    container_name: glances
