version: '3.3'

services:
  flume:
    build:
      context: ./flume
    image: flume:1.9.0
    restart: always
    #    volumes:
    #      - "./flume/flume.conf:/etc/flume/flume.conf"
    #      - "./keytool/pki/jks/truststore.jks:/etc/jks/truststore.jks"
    #      - "./kafka/jaas/kafka_client_jaas.conf:/root/.java.login.config"
    ports:
      - "24001:24001"