version: '3.3'
services:
  confluence:
    image: haxqer/confluence:7.19.14
    container_name: confluence-srv
    environment:
      - TZ=Asia/Shanghai
    #      - JVM_MINIMUM_MEMORY=1g
    #      - JVM_MAXIMUM_MEMORY=12g
    #      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - mysql
    ports:
      - "8090:8090"
    volumes:
      #- '/data/confluence:/var/confluence'
      - './backups:/var/atlassian/application-data/confluence/backups'
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-confluence
    ports:
      - "3307:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=confluence
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=confluence
      - MYSQL_PASSWORD=123123
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin', '--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=256M', '--max_allowed_packet=256M','--log_bin_trust_function_creators=1']
    volumes:
      - '/data/mysql:/var/lib/mysql'
    restart: always