version: '3.3'
services:
  zookeeper:
    # wurstmeister/zookeeper在下面这个操作系统下启动CPU占用 100%, 内存占用也过高
    # Linux version 5.14.0-427.26.1.el9_4.x86_64 (mockbuild@x64-builder01.almalinux.org) (gcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3), GNU ld version 2.35.2-43.el9) #1 SMP PREEMPT_DYNAMIC Wed Jul 17 15:51:13 EDT 2024
    # image: wurstmeister/zookeeper
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          #使用的容器的CPU核心数量或百分比
          cpus: '0.1'
          #可以使用的具体CPU核心1~3
          #cpuset: '0-3'
          #内存上限为1G
          memory: 2G
          #内存+swap内存总上限为2G
          #memswap_limit: 4G
        #reservations:
          #内存预留为256M
         # memory: 512M
          # 保留的CPU使用量为10%
          #cpus: "0.1"
  # docker exec -it kafka /bin/sh
  # cd opt/kafka_2.13-2.8.1
  # 创建topic
  # bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic partopic
  # 生产者发送消息
  # bin/kafka-console-producer.sh --broker-list kafka:9092 --topic partopic
  # 消费者消费消息
  # bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic partopic --from-beginning
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          #使用的容器的CPU核心数量或百分比
          cpus: '0.1'
          #内存上限为1G
          memory: 2G
    environment:
      # 广播主机名称，一般用IP指定
      KAFKA_ADVERTISED_HOST_NAME: ${HOST}
      # Zookeeper连接地址，格式：zoo1：port1,zoo2:port2:/path
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Kafka启动所使用的的协议及端口
      KAFKA_ADVERTISED_PORT: 9092
      # 日志文件保存120个小时
      KAFKA_LOG_RETENTION_HOURS: 120
      # broker的topic分区leader接受数据的时候，允许的单条消息的最大值，默认为1M
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      # broker端的leader分区在想其他follower分区复制消息时候 ，允许的单条消息的最大值
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      # topic的分区数
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DELETE_RETENTION_MS: 1000
      # Kafka广播地址及端口，告诉客户端，使用什么地址和端口能连接到Kafka，不指定，宿主机以外的客户端将无法连接到Kafka
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST}:9092
      KAFKA_BROKER_ID: 1
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    environment:
      ZK_HOSTS: ${HOST}
    ports:
      - "9009:9000"
    depends_on:
      - zookeeper
      - kafka
    deploy:
      resources:
        limits:
          #使用的容器的CPU核心数量或百分比
          cpus: '0.3'
          #内存上限为1G
          #memory: 2G
