version: '3.3'

services:
  gbase:
    image: "liaosnet/gbase8s"
    container_name: "gbase8s"
    privileged: true
    ports:
      - 9088:9088
    #  - 9200:9200
    #  - 9300:9300
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 4G