version: '3.3'
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - './data:/var/lib/postgresql/data'
    restart: always
