version: '3.3'

# https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docker.html
services:
  es01:
    image: ${STACK_IMAGE}
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data01:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 2G
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: ${STACK_IMAGE}
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data02:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 2G
    networks:
      - elastic
  es03:
    image: ${STACK_IMAGE}
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data03:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 2G
    networks:
      - elastic

  kibana:
    networks:
      - elastic
    depends_on:
      - es01
      - es02
      - es03
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - ./kibanadata:/usr/share/kibana/data
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
    mem_limit: ${MEM_LIMIT}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 2G
    cap_add:
      - ALL
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 30s
      retries: 120

networks:
  elastic:
    driver: bridge