version: '3.3'

# 内网穿透工具
services:
  frps:
    restart: unless-stopped
    network_mode: host
    volumes:
      - './frps.ini:/etc/frp/frps.ini'
    container_name: frps
    image: snowdreamtech/frps