version: '3.3'

# 网站导航工具
services:
  dashy:
    image: lissy93/dashy:latest
    ports:
      - '8001:80'
    container_name: dashy
    restart: unless-stopped
    volumes:
      - './public:/app/public'
