version: '3.3'

services:
  hive:
    image: apache/hive:${HIVE_VERSION}
    container_name: hive
    ports:
      - 10000:10000
      - 10002:10002
      - 9083:9083
    environment:
      - SERVICE_NAME=${SERVICE_NAME}
# https://archive.apache.org/dist/hive/hive-3.1.3/apache-hive-3.1.3-bin.tar.gz
#    volumes:
#      - '/opt/docker/hive/apache-hive-3.1.3-bin/conf:/opt/hive/conf'
#      - '/opt/docker/hive/apache-hive-3.1.3-bin/lib:/opt/hive/lib'