version: '3.3'
services:
  jobmanager:
    image: flink
    container_name: jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    restart: always
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    image: flink
    container_name: taskmanager
    restart: always
    expose:
      - "6121"
      - "6122"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"

