version: '3.3'

# 代码审查
# 账号密码: admin/admin
services:
  sonarqube:
    image: sonarqube:9.1.0-community
    container_name: sonarqube
    restart: always
    ports:
      - '11003:9000'
    volumes:
      - './data:/opt/sonarqube/data'
      - './logs:/opt/sonarqube/logs'
      - './extensions:/opt/sonarqube/extensions'
    environment:
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=root
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonarqube
