version: '3.3'
services:
  mysql:
    container_name: mysql
    volumes:
      #- 'mysql-conf:/etc/mysql/conf.d'
      - 'mysql-logs:/logs'
     # - 'mysql-data:/var/lib/mysql'
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
#      - './conf:/etc/mysql/conf.d'
#      - './logs:/logs'
#      - './data:/var/lib/mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=Ysj666666'
    ports:
      - '3306:3306'
    image: 'mysql:latest'

volumes:
  mysql-conf:
  mysql-logs:
  mysql-data:
