version: '3.3'
services:
  grafana:
    ports:
      - '3001:3000'
    volumes:
      - 'grafana-data:/var/lib/grafana'
    environment:
      - 'GF_SERVER_ROOT_URL=http://grafana.server.name'
      #- 'GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,grafana-simple-json-datasource 1.2.3'
      - 'GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel'
    image: 'grafana/grafana:latest'

volumes:
  grafana-data: