version: '3.3'

# maven私服
services:
  nexus:
    image: 'sonatype/nexus3'
    container_name: nexus
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '8931:8081'
    volumes:
      - 'nexus-data:/nexus-data'

volumes:
  nexus-data: